// <auto-generated />
using System;
using GymBrain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymBrain.Infrastructure.Migrations
{
    [DbContext(typeof(GymBrainDbContext))]
    [Migration("20260305004440_ExpandExerciseCatalogAndEquipment")]
    partial class ExpandExerciseCatalogAndEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymBrain.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DefaultBeginnerWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetMuscle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Barbell Bench Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000002"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Incline Barbell Bench Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000003"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Bench Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000004"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Incline Dumbbell Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000005"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Cable Fly",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000006"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "machine",
                            Name = "Pec Deck",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000007"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Push-Up",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000008"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "machine",
                            Name = "Smith Machine Flat Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000009"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "machine",
                            Name = "Smith Machine Incline Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000010"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Barbell Deadlift",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000011"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Barbell Row",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000012"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Pull-Up",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000013"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 25.0,
                            Equipment = "cable",
                            Name = "Lat Pulldown",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000014"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "cable",
                            Name = "Seated Cable Row",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000015"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Row",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000016"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "T-Bar Row",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000017"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Straight-Arm Pulldown",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000018"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Back Extension",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000019"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Chin-Up",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000020"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "barbell",
                            Name = "Overhead Press",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000021"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Shoulder Press",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000022"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "dumbbell",
                            Name = "Lateral Raise",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000023"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "cable",
                            Name = "Cable Lateral Raise",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000024"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Face Pull",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000025"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "dumbbell",
                            Name = "Front Raise",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000026"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "machine",
                            Name = "Reverse Pec Deck",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000027"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Arnold Press",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000028"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "cable",
                            Name = "Cable Shrug",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000029"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Barbell Squat",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000030"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 40.0,
                            Equipment = "machine",
                            Name = "Leg Press",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000031"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "machine",
                            Name = "Leg Extension",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000032"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "machine",
                            Name = "Hack Squat",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000033"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "dumbbell",
                            Name = "Goblet Squat",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000034"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Lunges",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000035"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Bulgarian Split Squat",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000036"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Romanian Deadlift",
                            TargetMuscle = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000037"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "machine",
                            Name = "Leg Curl",
                            TargetMuscle = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000038"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Hip Thrust",
                            TargetMuscle = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000039"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Glute Bridge",
                            TargetMuscle = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000040"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "cable",
                            Name = "Cable Pull-Through",
                            TargetMuscle = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000041"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "barbell",
                            Name = "Barbell Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000042"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000043"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 6.0,
                            Equipment = "dumbbell",
                            Name = "Incline Dumbbell Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000044"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "dumbbell",
                            Name = "Hammer Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000045"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Cable Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000046"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Equipment = "barbell",
                            Name = "Preacher Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000047"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Tricep Pushdown",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000048"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "barbell",
                            Name = "Skull Crushers",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000049"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Equipment = "cable",
                            Name = "Cable Overhead Tricep Extension",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000050"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Tricep Kickback",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000051"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "barbell",
                            Name = "Close-Grip Bench Press",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000052"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Dips",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000053"),
                            Category = "Bodyweight",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Plank",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000054"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "cable",
                            Name = "Cable Crunch",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000055"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Hanging Leg Raise",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000056"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Ab Wheel Rollout",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000057"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "dumbbell",
                            Name = "Russian Twist",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000058"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "machine",
                            Name = "Standing Calf Raise",
                            TargetMuscle = "Calves"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000059"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "machine",
                            Name = "Seated Calf Raise",
                            TargetMuscle = "Calves"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000060"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Equipment = "barbell",
                            Name = "Barbell Shrug",
                            TargetMuscle = "Traps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000061"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "dumbbell",
                            Name = "Dumbbell Shrug",
                            TargetMuscle = "Traps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000062"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Equipment = "barbell",
                            Name = "Wrist Curl",
                            TargetMuscle = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000063"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 3.0,
                            Equipment = "barbell",
                            Name = "Reverse Wrist Curl",
                            TargetMuscle = "Forearms"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000064"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Equipment = "barbell",
                            Name = "Clean and Press",
                            TargetMuscle = "Full Body"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000065"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Equipment = "bodyweight",
                            Name = "Burpees",
                            TargetMuscle = "Full Body"
                        });
                });

            modelBuilder.Entity("GymBrain.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("encrypted_api_key");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LlmProvider")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredModel")
                        .HasColumnType("text");

                    b.Property<string>("TonePersona")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Motivational Coach");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymBrain.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
