// <auto-generated />
using System;
using GymBrain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymBrain.Infrastructure.Migrations
{
    [DbContext(typeof(GymBrainDbContext))]
    [Migration("20260304025015_AddWorkoutSession")]
    partial class AddWorkoutSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymBrain.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DefaultBeginnerWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetMuscle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Name = "Barbell Squat",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000002"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Name = "Barbell Deadlift",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000003"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Name = "Barbell Bench Press",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000004"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 15.0,
                            Name = "Overhead Press",
                            TargetMuscle = "Shoulders"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000005"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Name = "Barbell Row",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000006"),
                            Category = "Bodyweight",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Name = "Pull-Up",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000007"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Name = "Dumbbell Lunges",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000008"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 8.0,
                            Name = "Dumbbell Curl",
                            TargetMuscle = "Biceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000009"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Name = "Tricep Pushdown",
                            TargetMuscle = "Triceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000010"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 40.0,
                            Name = "Leg Press",
                            TargetMuscle = "Quadriceps"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000011"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 25.0,
                            Name = "Lat Pulldown",
                            TargetMuscle = "Back"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000012"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 10.0,
                            Name = "Cable Fly",
                            TargetMuscle = "Chest"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000013"),
                            Category = "Bodyweight",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 0.0,
                            Name = "Plank",
                            TargetMuscle = "Core"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000014"),
                            Category = "Compound",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 20.0,
                            Name = "Romanian Deadlift",
                            TargetMuscle = "Hamstrings"
                        },
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000015"),
                            Category = "Isolation",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultBeginnerWeightKg = 5.0,
                            Name = "Lateral Raise",
                            TargetMuscle = "Shoulders"
                        });
                });

            modelBuilder.Entity("GymBrain.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("encrypted_api_key");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LlmProvider")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredModel")
                        .HasColumnType("text");

                    b.Property<string>("TonePersona")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Motivational Coach");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymBrain.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
